matrix:
  include:
  - os: linux
    language: python
    python:
      - '3.5'
      - '3.6'
    sudo: required
    before_install: chmod +x .ci/build_linux_wheels.sh
    env:
      - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
      - DIST_FOLD=wheelhouse
    install:
      - pip install numpy
      - docker pull $DOCKER_IMAGE
    script:
      - docker run --rm -it -v $(pwd):/io -w /io quay.io/pypa/manylinux1_x86_64 .ci/build_linux_wheels.sh
    after_success:
      - pip install twine
   
  - os: osx
    osx_image: xcode9.4
    language: generic
    sudo: required
    before_install: chmod +x .ci/build_macos_wheels.sh
    env:
      - DIST_FOLD=dist
    script: ".ci/build_macos_wheels.sh"
    after_success:
      - pip install twine --user
      
  - os: osx
    osx_image: xcode8
    language: generic
    sudo: required
    before_install: chmod +x .ci/build_macos_wheels.sh
    env:
      - DIST_FOLD=dist
    script: ".ci/build_macos_wheels.sh"
    after_success:
      - pip install twine --user
    
deploy:
  provider: script 
  script:
    - python -m twine upload -u cimba -p $TWINE_PASSWORD $DIST_FOLD/*
  skip_cleanup: true
  on:
    tags: true
  