
name: Test Pymef

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
        pip install numpy

    - name: Test package
      run:
        python setup.py test

  release:
    if: contains(github.ref, 'refs/tags/')
    needs: test

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        buildplat:
          - [ubuntu-20.04, manylinux_x86_64]
          - [ubuntu-20.04, musllinux_x86_64]
          - [macos-11, macosx_x86_64]
          - [windows-2019, win_amd64]
        python: ["cp36", "cp37", "cp38", "cp39", "cp310", "cp311"]

    steps:

    - uses: actions/checkout@v2

    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheel
        pip install setuptools
        pip install numpy
        pip install twine

    - name: Build wheels
      runs-on: ${{ matrix.buildplat[0] }}
      run: python -m cibuildwheel --output-dir dist/
      env:
        CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}

    - name: Publish package
      runs-on: ${{ matrix.buildplat[0] }}
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload --skip-existing dist/pymef*


